version: '3.3'
services:
  servico1:
    container_name: servico1
    build:
      context: ./servico1/
      dockerfile: Dockerfile
    volumes:
      - './servico1/:/var/www/html/'
    ports:
      - '8001:80'
      
  servico2:
    container_name: servico2
    build:
      context: ./servico2/
      dockerfile: Dockerfile
    volumes:
      - './servico2/:/var/www/html/'
    ports:
      - '8002:80'

  servico3:
    container_name: servico3
    build:
      context: ./servico3/
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - './servico3/:/var/www/html/'
    ports:
      - '8003:80'

  db:
    container_name: db
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3303:3306'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8083:80'
    volumes:
      - './phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini' 
